HEADERS += \
    $$PWD/TitleBar/titlewidget.h \
    $$PWD/TitleBar/searchlineedit.h \
    $$PWD/BottomBar/bottomwidget.h \
    $$PWD/midwidget.h \
    $$PWD/MidLeftWidget/lefttoolbar.h \
    $$PWD/TitleBar/mymenu.h \
    $$PWD/MidLeftWidget/midleftwidget.h \
    $$PWD/MidRightWidget/midrightwidget.h \
    $$PWD/MidRightWidget/musiclyricwidget.h \
    $$PWD/Common/toolbutton.h \
    $$PWD/MidRightWidget/mvwidget.h    \
    $$PWD/BottomBar/sliderwidget.h \
    $$PWD/MidLeftWidget/localList/locallistwidget.h \
    $$PWD/Common/menu.h \
    $$PWD/BottomBar/play_mode_menu.h \
    $$PWD/aboutkugoudialog.h \
    $$PWD/SkinWidget/skinwidget.h \
    $$PWD/Common/pushbutton.h \
    $$PWD/MidLeftWidget/moretools/moretoolwidget.h \
    $$PWD/MidLeftWidget/phonemanage/phonemanagewidget.h \
    $$PWD/TitleBar/rightmenu.h \
    $$PWD/SystemTray/kugousystemtray.h \
    $$PWD/SystemTray/voicebutton.h \
    $$PWD/SystemTray/musictraybutton.h  \
    $$PWD/RemoteWidget/remotewidget.h \
    $$PWD/RemoteWidget/core/musicabstractremotewidget.h \
    $$PWD/RemoteWidget/core/musicabstractremotebutton.h \
    $$PWD/MidLeftWidget/localList/treemodel.h \
    $$PWD/MidLeftWidget/download/downloadwidget.h \
    $$PWD/MidLeftWidget/download/mydownloadwidget.h \
    $$PWD/MidLeftWidget/download/localimportwidget.h \
    $$PWD/MidLeftWidget/networkCollect/networkcollectwidget.h \
    $$PWD/MidLeftWidget/musicRadio/musicradiowidget.h \
    $$PWD/MidLeftWidget/musicRadio/mvradiowidget.h \
    $$PWD/Common/abstracttabwidget.h \
    $$PWD/MidRightWidget/radioWidget/radiowidget.h \
    $$PWD/RemoteWidget/nextmusicwidget.h \
    $$PWD/RemoteWidget/core/abstractwidget.h \
    $$PWD/RemoteWidget/previousmusicwidget.h \
    $$PWD/RemoteWidget/openkugouwidget.h \
    $$PWD/RemoteWidget/desktopphotowidget.h \
    $$PWD/RemoteWidget/playmusicwidget.h \
    $$PWD/RemoteWidget/rightremotemenu.h

SOURCES += \
    $$PWD/TitleBar/titlewidget.cpp \
    $$PWD/TitleBar/searchlineedit.cpp \
    $$PWD/BottomBar/bottomwidget.cpp \
    $$PWD/midwidget.cpp \
    $$PWD/MidLeftWidget/lefttoolbar.cpp \
    $$PWD/TitleBar/mymenu.cpp \
    $$PWD/MidLeftWidget/midleftwidget.cpp \
    $$PWD/MidRightWidget/midrightwidget.cpp \
    $$PWD/MidRightWidget/musiclyricwidget.cpp \
    $$PWD/Common/toolbutton.cpp \
    $$PWD/MidRightWidget/mvwidget.cpp  \
    $$PWD/BottomBar/sliderwidget.cpp \
    $$PWD/MidLeftWidget/localList/locallistwidget.cpp \
    $$PWD/Common/menu.cpp \
    $$PWD/BottomBar/play_mode_menu.cpp \
    $$PWD/aboutkugoudialog.cpp  \
    $$PWD/SkinWidget/skinwidget.cpp \
    $$PWD/Common/pushbutton.cpp \
    $$PWD/MidLeftWidget/moretools/moretoolwidget.cpp \
    $$PWD/MidLeftWidget/phonemanage/phonemanagewidget.cpp \
    $$PWD/TitleBar/rightmenu.cpp \
    $$PWD/SystemTray/kugousystemtray.cpp \
    $$PWD/SystemTray/voicebutton.cpp \
    $$PWD/SystemTray/musictraybutton.cpp \
    $$PWD/RemoteWidget/remotewidget.cpp \
    $$PWD/RemoteWidget/core/musicabstractremotewidget.cpp \
    $$PWD/RemoteWidget/core/musicabstractremotebutton.cpp \
    $$PWD/MidLeftWidget/localList/treemodel.cpp \
    $$PWD/MidLeftWidget/download/downloadwidget.cpp \
    $$PWD/MidLeftWidget/download/mydownloadwidget.cpp \
    $$PWD/MidLeftWidget/download/localimportwidget.cpp \
    $$PWD/MidLeftWidget/networkCollect/networkcollectwidget.cpp \
    $$PWD/MidLeftWidget/musicRadio/musicradiowidget.cpp \
    $$PWD/MidLeftWidget/musicRadio/mvradiowidget.cpp \
    $$PWD/Common/abstracttabwidget.cpp \
    $$PWD/MidRightWidget/radioWidget/radiowidget.cpp \
    $$PWD/RemoteWidget/nextmusicwidget.cpp \
    $$PWD/RemoteWidget/core/abstractwidget.cpp \
    $$PWD/RemoteWidget/previousmusicwidget.cpp \
    $$PWD/RemoteWidget/openkugouwidget.cpp \
    $$PWD/RemoteWidget/desktopphotowidget.cpp \
    $$PWD/RemoteWidget/playmusicwidget.cpp \
    $$PWD/RemoteWidget/rightremotemenu.cpp
